# Generated by Django 5.0.6 on 2024-12-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('gdetails', models.CharField(max_length=100, verbose_name='Product Detail')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
